services:
  tailscale:
    image: tailscale/tailscale:v1.92.5
    container_name: ts-searxng
    hostname: ${HOSTNAME:?Environment variable HOSTNAME must be set}
    restart: unless-stopped
    networks:
      - searxng
    dns:
      - 100.100.100.100
      - 1.1.1.1
      - 9.9.9.9
    volumes:
      - ./config/tailscale:/config
      - ./data/tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY:?Environment variable TS_AUTHKEY must be set}?ephemeral=false
      - "TS_EXTRA_ARGS=--advertise-tags=tag:container --reset"
      - TS_SERVE_CONFIG=/config/tailscale.json
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    cap_add:
      - net_admin

  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    restart: unless-stopped
    depends_on:
      - tailscale
      - valkey
    network_mode: service:tailscale
    volumes:
      - ./config/searxng:/etc/searxng
      - ./data/searxng:/var/cache/searxng
    environment:
      - SEARXNG_BASE_URL=https://${HOSTNAME:?Environment variable HOSTNAME must be set}.${DOMAIN:?Environment variable DOMAIN must be set}/
      - SEARXNG_SECRET=${SEARXNG_SECRET:?Environment variable SEARXNG_SECRET must be set}
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  valkey:
    image: docker.io/valkey/valkey:8-alpine
    container_name: searxng-valkey
    command: valkey-server --save 30 1 --loglevel warning
    restart: unless-stopped
    networks:
      - searxng
    volumes:
      - ./data/valkey:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

networks:
  searxng:
